# DataScope MongoDB 示例配置
server:
  port: 8084

spring:
  application:
    name: data-scope-mongodb-example
  mongodb:
    uri: mongodb://user:123456@172.24.20.15:27017/test?authSource=admin&authMechanism=SCRAM-SHA-1

# 数据范围管理配置
structure:
  data-scope:
    field-config:
      org-id-field: orgId
      dept-id-field: deptId
      user-id-field: userId
    enabled: true
    scan-packages:
      - cn.structured.datascope.example.mongodb.document
logging:
  level:
    cn.structured.datascope: DEBUG
    cn.structured.datascope.example.mongodb: DEBUG
    root: INFO