server:
  port: 8087

spring:
  application:
    name: data-scope-message-example
  autoconfigure:
    exclude:
      - org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration
  rabbitmq:
    host: 172.24.20.15
    port: 5672
    username: root
    password: 123456


  cloud:
    stream:
      function:
        definition: orderEventInput
      bindings:
        orderEventInput-in-0:
          destination: order-exchange
          content-type: application/json
        orderEventOutput-out-0:
          destination: order-exchange
          content-type: application/json

structure:
  data-scope:
    enabled: true
    field-config:
      org-id-field: orgId
      dept-id-field: deptId

logging:
  level:
    cn.structured.datascope: DEBUG
    cn.structured.datascope.example.message: DEBUG
    org.springframework.cloud.stream: DEBUG
    root: INFO